#!/bin/python3

import sys


n = int(input().strip())
a = []
m = n
for a_i in range(n):
    a_t = [int(a_temp) for a_temp in input().strip().split(' ')]
    a.append(a_t)

primary = 0
secondary = 0
while m > 0:
    primary += a[m-1][m-1]
    m -= 1

while n > 0:
    secondary += a[m][n-1]
    n -= 1
    m +=1
    
total = abs(primary - secondary)
print(total)
