#!/bin/python3

import sys


x1,v1,x2,v2 = input().strip().split(' ')
x1,v1,x2,v2 = [int(x1),int(v1),int(x2),int(v2)]
count = 0

while x1 != x2 and count in range(0,10000):
    
    x1 += v1
    x2 += v2
    count += 1
    if x1 == x2:
        print('YES')
if x1 != x2:
        print('NO')


        
