#!/bin/python3

import sys


n = int(input().strip())
arr = [int(arr_temp) for arr_temp in input().strip().split(' ')]

poscount = 0
negcount = 0
zerocount = 0
for x in arr:
    if x > 0:
        poscount += 1
    if x < 0:
        negcount += 1
    if x == 0:
        zerocount += 1
        
print(poscount/n)
print(negcount/n)
print(zerocount/n)
